// import {useContext} from 'react'
import Head from "next/head";
import Link from "next/link";

import { getSession, withPageAuthRequired } from "@auth0/nextjs-auth0";

import { dehydrate, QueryClient } from "@tanstack/react-query";
import { fetchProducts } from "@/lib/api-functions/server/products/queries";
import { STORAGE_KEY } from "@/lib/tq/products/settings";

import { log } from "@/lib/utils/formatters";

import { checkPermissions } from "@/lib/api-functions/server/utils";
import settings from "@/lib/api-functions/server/permissions";

import Layout from "@/components/Layout";
import Heading from "@/components/Heading";
import QueryBoundaries from "@/components/QueryBoundaries";
import ProductList from "@/components/ProductList";
import { Button, ButtonGroup } from "@/components/mui";
import { useDelete } from "@/lib/tq/products/mutations";
// import { UIContext } from '@/components/contexts/UI.context';

export default function AdminProductList({ user }) {
  return (
    <>
      <Head>
        <title>Admin Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component="h2">Admin Home</Heading>

        <ButtonGroup
          variant="contained"
          aria-label="outlined primary button group"
        >
          <Button
            variant="contained"
            component={Link}
            href={`/admin/products/`}
          >
            List Products
          </Button>
          <Button
            variant="contained"
            component={Link}
            href={`/admin/products/add`}
          >
            Add Product
          </Button>
          <Button variant="contained" component={Link} href={`/admin/baskets/`}>
            List Baskets
          </Button>
          <Button variant="contained" component={Link} href={`/admin/orders/`}>
            List Orders
          </Button>
        </ButtonGroup>
      </Layout>
    </>
  );
}

export const getServerSideProps = withPageAuthRequired({
  async getServerSideProps() {
    return {
      props: {},
    };
  },
});
