import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Button, EditIcon } from "@/components/mui";
import Layout from "@/components/Layout";
import Heading from "@/components/Heading";
import Paragraph from "@/components/Paragraph";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component="h2" >
          index
        </Heading>
        <Paragraph>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aut, rerum
          perferendis velit ducimus, quisquam quam harum nam magni provident
          cumque magnam sed in minima iure reiciendis repudiandae aperiam?
          Libero, rerum.
        </Paragraph>
        <Button variant="contained">
          <EditIcon />
          index
        </Button>
      </Layout>
    </>
  );
}
